version: "3"

services:

  database:
    image: postgres:latest # use latest official postgres version
    container_name: postgreeDB
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: pablo
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - database-data-2:/var/lib/postgresql/data/ # persist data even
  mosquitto:
    image: iegomez/mosquitto-go-auth:latest
    container_name: mqtt
    volumes:
      - ./conf:/etc/mosquitto
    ports:
      - 1883:1883
      - 1884:1884

volumes:
  redisdata:
  database-data-2: # named volumes can be managed easier using docker-compose
