version: "3"

services:

  redis:
    image: redis:5-alpine
    command: redis-server --requirepass password
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
  mosquitto:
    image: iegomez/mosquitto-go-auth:latest
    volumes:
      - ./conf:/etc/mosquitto
    ports:
      - 1883:1883
      - 1884:1884

volumes:
  redisdata:
